source 'https://github.com/funkyHS/FunkyFMSpecs.git'  #私有的远程代码仓库
source 'https://github.com/CocoaPods/Specs.git'  #官方仓库的地址

use_frameworks!

target 'FunkyFMMine_Example' do
  pod 'FunkyFMMine', :path => '../'

  target 'FunkyFMMine_Tests' do
    inherit! :search_paths

    
  end
end
